app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.characters, name='characters'),
    path('fight/', views.fight, name='fight'),
    path('notes/', views.notes, name='notes'),
    path('history/', views.history, name='history')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponse
from django.shortcuts import render

def characters(request):
    context = {
        'title' : 'Персонажи',
    }
    return render(request, 'main/characters.html', context)

def fight(request):
    return render(request, 'main/fight.html')

def notes(request):
    return render(request, 'main/notes.html')

def history(request):
    return render(request, 'main/history.html')

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link 
            rel="stylesheet" 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
            crossorigin="anonymous"
        />
    <link rel="stylesheet" href="{% static "deps/css/base.css" %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-nav">
            <a class="nav-item nav-link" id="characters" href="{% url "main:characters" %}">Персонажи</a>
            <a class="nav-item nav-link" id="characters" href="{% url "main:fight" %}">Режим Боя</a>
            <a class="nav-item nav-link" id="characters" href="{% url "main:notes" %}">Заметки</a>
            <a class="nav-item nav-link" id="characters" href="{% url "main:history" %}">История</a>
        </div>
    </nav>
    {% block content %}{% endblock %}

main/templates/main/characters.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}
<div class="maindiv">
    <div class="left">
        <div class="character">Мелиса</div>
        <div class="character">Василиск</div>
        <div class="character">Перегар</div>
        <div class="character">Алик</div>
        <div class="character">Ки Са</div>
        <div class="character">Горелый Овощ</div>
    </div>
    <div class="right">
        <div class="image_name">
            <img src="{% static "deps/image/melisa.jpg" %}" height="150px" width="150px">
            <p1>Мелиса</p1>
        </div>
        <div class="main_infromation">
            <div class="main_information_item">
                <p1>Класс : Бард</p1>
                <button class="main_information_item_button"></button>
            </div>
            <div class="main_information_item">
                <p1>Уровень : 5</p1>
                <button class="main_information_item_button"></button>
            </div>
            <div class="main_information_item">
                <p1>Опыт : 1700</p1>
                <button class="main_information_item_button"></button>
            </div>
            <div class="main_information_item">
                <p1>Максимально ХП : 50</p1>
                <button class="main_information_item_button"></button>
            </div>
            <div class="main_information_item">
                <p1>Текущее ХП : 50</p1>
                <button class="main_information_item_button"></button>
            </div>
        </div>  
        <div class="optional_information"></div>
    </div>
{% endblock  %}

main/templates/main/fight.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}
<div class="maindiv"></div>
{% endblock  %}

main/templates/main/history.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}
<div class="maindiv"></div>
{% endblock  %}

main/templates/main/notes.html
{% extends "main/base.html" %}

{% load static %}

{% block content %}
<div class="maindiv"></div>
{% endblock  %}